version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      # Monta tus PDFs y el índice FAISS
      - "./data:/app/data"
    ports:
      - "8000:8000"
    # Asegura que el front espere al backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/health || exit 1"]
      interval: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env.local
    volumes:
      # Para hot-reload y poder editar en caliente
      - "./frontend:/app"
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    name: wealth_insights_net
