version: "3.9"
services:
  backend:
    build: ../backend
    ports: ["8000:8000"]
    env_file: ../backend/.env
    volumes:
      - ../data:/app/data  # persistencia de PDFs e índice
  frontend:
    build: ../frontend
    ports: ["3000:3000"]
    depends_on: [backend]
