version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env.dev               #ó .env.prod en producción
    volumes:
      - ./backend/data:/app/data       #PDFs + índice FAISS
      - ./backend/logs:/app/logs
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/health || exit 1"]
      interval: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env.local
    volumes:
      - ./frontend:/app                #hot-reload en dev
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    name: wealth_insights_net
