name: CD-prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # Build & push backend image
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags: ghcr.io/your-org/wealth-backend:latest
          push: true
          build-args: |
            ENV=prod

      # Build & push frontend image
      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          tags: ghcr.io/your-org/wealth-frontend:latest
          push: true

      #espliegue (ECS, K8s, Render, etc.)
      # - name: Deploy to AWS ECS ...
      #   run: your-deployment-script.sh
